# Makefile.deps created Fri Feb 22 12:56:10 PST 2013
debugf.o: debugf.c debugf.h
hashset.o: hashset.c debugf.h hashset.h strhash.h
strhash.o: strhash.c strhash.h
spellchk.o: spellchk.c debugf.h hashset.h yyextern.h
